In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
from scipy import stats
import numpy as np
import requests
import pandas as pd
import json
from citipy import citipy
import random

# Import API key
from config import api_key

In [2]:
sensors_df = pd.read_csv("PCS_Locations.csv")
sensors_df

,sensor_id,sensor_description,sensor_name,installation_date,status,note,direction_1,direction_2,latitude,longitude,location
0,55,Elizabeth St-La Trobe St (East),Eli380_T,2018/07/19,A,NaN,North,South,-37.809889,144.961343,"(-37.80988941, 144.96134331)"
1,45,Little Collins St-Swanston St (East),Swa148_T,2017/06/29,A,NaN,North,South,-37.814141,144.966094,"(-37.81414074, 144.9660938)"
2,61,RMIT Building 14,RMIT14_T,2019/06/28,A,NaN,North,South,-37.807675,144.963091,"(-37.80767455, 144.96309115)"
3,7,Birrarung Marr,Fed_T,2014/12/17,A,NaN,East,West,-37.818629,144.971694,"(-37.81862929, 144.97169395)"
4,72,Flinders St- ACMI,ACMI_T,2020/11/30,A,NaN,East,West,-37.817263,144.968728,"(-37.81726337, 144.96872809)"
...,...,...,...,...,...,...,...,...,...,...,...
69,51,QVM-Franklin St (North),Fra118_T,2017/11/30,A,NaN,West,East,-37.808418,144.959063,"(-37.80841814, 144.95906317)"
70,10,Victoria Point,BouHbr_T,2009/04/23,A,NaN,West,East,-37.818765,144.947105,"(-37.81876473, 144.94710545)"
71,43,Monash Rd-Swanston St (West),UM2_T,2015/04/15,A,NaN,South,North,-37.798445,144.964118,"(-37.79844525, 144.96411782)"
72,73,Bourke St - Spencer St (South),Bou655_T,2020/10/02,A,NaN,West,East,-37.816957,144.954154,"(-37.81695684, 144.95415373)"
73,75,Spring St- Flinders st (West),SprFli_T,2020/12/18,A,NaN,North,South,-37.815153,144.974677,"(-37.81515275, 144.97467662)"

In [12]:
sensors_df["sensor_description"].unique()

array(['Elizabeth St-La Trobe St (East)',
       'Little Collins St-Swanston St (East)', 'RMIT Building 14',
       'Birrarung Marr', 'Flinders St- ACMI', 'La Trobe St (North)',
       '231 Bourke St', 'Sandridge Bridge',
       'Flinders La-Swanston St (West)',
       'Melbourne Convention Exhibition Centre',
       'Flinders La - Swanston St (West) Temporary',
       'Royal Pde - Grattan St', 'Alfred Place', 'Collins Place (South)',
       'Swanston St - City Square', 'State Library - New',
       'State Library', 'Flinders Ln -Degraves St (South)',
       'Melbourne Central-Elizabeth St (East)', 'Lincoln-Swanston (West)',
       'Flinders Ln -Degraves St (North)',
       'Flinders Ln -Degraves St (Crossing)', 'Melbourne Central',
       'St Kilda Rd-Alexandra Gardens', 'Errol Street (East)',
       'Westwood Place', 'Bourke St-Russell St (West)',
       'Spencer St-Collins St (South)', 'Flinders St-Spring St (West)',
       'Flagstaff Station', 'New Quay', 'Collins Street (North)',
       'Southern Cross Station', 'Lonsdale St (South)',
       'Flinders Street Station Underpass',
       'Flinders St-Swanston St (West)', 'City Square',
       'Town Hall (West)', 'Pelham St (South)',
       'Lonsdale St - Elizabeth St (North)',
       'Grattan St-Swanston St (West)', 'Princes Bridge',
       'Faraday St-Lygon St (West)', 'Elizabeth St-Lonsdale St (South)',
       'Bourke Street Mall (South)', 'Southbank',
       'Bourke Street Mall (North)', 'Building 80 RMIT',
       'Chinatown-Lt Bourke St (South)', 'Flinders St-Spark La',
       'Bourke St Bridge', 'Lonsdale St-Spring St (West)',
       'Lygon St (West)', 'Chinatown-Swanston St (North)',
       'Lygon St (East)', 'Queen St (West)',
       'Bourke St - Spencer St (North)', 'Webb Bridge', 'Waterfront City',
       'Collins Place (North)', 'QVM-Therry St (South)',
       'QV Market-Elizabeth St (West)', 'Australia on Collins',
       'Flinders St-Elizabeth St (East)', 'Spencer St-Collins St (North)',
       'QV Market-Peel St', 'The Arts Centre',
       'Tin Alley-Swanston St (West)', 'QVM-Queen St (East)',
       'QVM-Franklin St (North)', 'Victoria Point',
       'Monash Rd-Swanston St (West)', 'Bourke St - Spencer St (South)',
       'Spring St- Flinders st (West)'], dtype=object)

In [13]:
# Only use the following 9 sensors:
sensors_reduced = sensors_df.copy()
sensors_reduced = sensors_reduced.loc[(sensors_reduced["sensor_description"] == "Town Hall (West)") | 
                                        (sensors_reduced["sensor_description"] == "Spencer St-Collins St (North)") |
                                        (sensors_reduced["sensor_description"] == "Southbank") |
                                        (sensors_reduced["sensor_description"] == "Collins Street (North)") | 
                                        (sensors_reduced["sensor_description"] == "Bourke St-Russell St (West)") |
                                        (sensors_reduced["sensor_description"] == "Chinatown-Lt Bourke St (South)") |
                                        (sensors_reduced["sensor_description"] == "Flinders St-Spark La") | 
                                        (sensors_reduced["sensor_description"] == "QVM-Franklin St (North)") |
                                        (sensors_reduced["sensor_description"] == "Lygon St (East)") 
                                         ,:]
sensors_reduced[["sensor_id","sensor_description"]]

    sensor_id              sensor_description
26         21     Bourke St-Russell St (West)
31         53          Collins Street (North)
37          4                Town Hall (West)
45         35                       Southbank
48         20  Chinatown-Lt Bourke St (South)
49         34            Flinders St-Spark La
54         37                 Lygon St (East)
64         24   Spencer St-Collins St (North)
69         51         QVM-Franklin St (North)

In [14]:
# Base URL required for API call
url = "https://developers.zomato.com/api/v2.1/search?"

# Parameters to run through Query URL
start = np.arange(0,60,20)
count = 20
city = 259
radius = 150
b = 0

In [15]:
# Latitude and Longitudes of Sensor Locations:
lat = list(sensors_reduced["latitude"])
lon = list(sensors_reduced["longitude"])

In [16]:
# Empty list to hold all API calls
response_data = []

In [17]:
# Loop through Zomato API
for a in range(len(start)):
    for b in range(len(lat)):
        query_url = f"{url}entity_id={city}&entity_type=metro&lat={lat[b]}&lon={lon[b]}&radius={radius}&sort=real_distance&apikey={api_key}&start={start[a]}&count={count}"
        response_data.append(requests.get(query_url).json())
        print(start[a], lat[b], lon[b])
    b += 1

0 -37.81244703 144.96778757
0 -37.8156419 144.965499
0 -37.81487988 144.9660878
0 -37.82017828 144.96508877
0 -37.81172913 144.96824660000001
0 -37.81537985 144.97415049999998
0 -37.80310271 144.96671452
0 -37.81887962 144.95449198
0 -37.80841814 144.95906317
20 -37.81244703 144.96778757
20 -37.8156419 144.965499
20 -37.81487988 144.9660878
20 -37.82017828 144.96508877
20 -37.81172913 144.96824660000001
20 -37.81537985 144.97415049999998
20 -37.80310271 144.96671452
20 -37.81887962 144.95449198
20 -37.80841814 144.95906317
40 -37.81244703 144.96778757
40 -37.8156419 144.965499
40 -37.81487988 144.9660878
40 -37.82017828 144.96508877
40 -37.81172913 144.96824660000001
40 -37.81537985 144.97415049999998
40 -37.80310271 144.96671452
40 -37.81887962 144.95449198
40 -37.80841814 144.95906317

In [24]:
len(response_data[26]["restaurants"])

20

In [42]:
# Empty list to hold all restaurant names, aggregate rating, hours of operation, type of eatery, price 
restr_names = []
rating = []
cuisine_type = []
price_range = []
restr_lat = []
restr_lon = []
sensor_loc = []
sensor_id = []
c = 0
d = 0
# Populate lists with JSON data from Zomato 
for c in range(len(response_data)):     
    if (c % 9 == 0):
        d = 0
    else:
        d = d
    for x in range(count):
        restr_names.append(response_data[c]["restaurants"][x]["restaurant"]["name"])
        rating.append(response_data[c]["restaurants"][x]["restaurant"]["user_rating"]["aggregate_rating"])
        cuisine_type.append(response_data[c]["restaurants"][x]["restaurant"]["cuisines"])
        price_range.append(response_data[c]["restaurants"][x]["restaurant"]["price_range"])
        restr_lat.append(response_data[c]["restaurants"][x]["restaurant"]["location"]["latitude"])
        restr_lon.append(response_data[c]["restaurants"][x]["restaurant"]["location"]["longitude"])
        sensor_id.append(list(sensors_reduced["sensor_id"])[d])
        sensor_loc.append(list(sensors_reduced["sensor_description"])[d])
        print(c,x,d)
    if (c % 9 != 9):
        d += 1 
    elif (c >= 9) & (c % 9 != 9):
        d += 1  
    c += 1

0 0 0
0 1 0
0 2 0
0 3 0
0 4 0
0 5 0
0 6 0
0 7 0
0 8 0
0 9 0
0 10 0
0 11 0
0 12 0
0 13 0
0 14 0
0 15 0
0 16 0
0 17 0
0 18 0
0 19 0
1 0 1
1 1 1
1 2 1
1 3 1
1 4 1
1 5 1
1 6 1
1 7 1
1 8 1
1 9 1
1 10 1
1 11 1
1 12 1
1 13 1
1 14 1
1 15 1
1 16 1
1 17 1
1 18 1
1 19 1
2 0 2
2 1 2
2 2 2
2 3 2
2 4 2
2 5 2
2 6 2
2 7 2
2 8 2
2 9 2
2 10 2
2 11 2
2 12 2
2 13 2
2 14 2
2 15 2
2 16 2
2 17 2
2 18 2
2 19 2
3 0 3
3 1 3
3 2 3
3 3 3
3 4 3
3 5 3
3 6 3
3 7 3
3 8 3
3 9 3
3 10 3
3 11 3
3 12 3
3 13 3
3 14 3
3 15 3
3 16 3
3 17 3
3 18 3
3 19 3
4 0 4
4 1 4
4 2 4
4 3 4
4 4 4
4 5 4
4 6 4
4 7 4
4 8 4
4 9 4
4 10 4
4 11 4
4 12 4
4 13 4
4 14 4
4 15 4
4 16 4
4 17 4
4 18 4
4 19 4
5 0 5
5 1 5
5 2 5
5 3 5
5 4 5
5 5 5
5 6 5
5 7 5
5 8 5
5 9 5
5 10 5
5 11 5
5 12 5
5 13 5
5 14 5
5 15 5
5 16 5
5 17 5
5 18 5
5 19 5
6 0 6
6 1 6
6 2 6
6 3 6
6 4 6
6 5 6
6 6 6
6 7 6
6 8 6
6 9 6
6 10 6
6 11 6
6 12 6
6 13 6
6 14 6
6 15 6
6 16 6
6 17 6
6 18 6
6 19 6
7 0 7
7 1 7
7 2 7
7 3 7
7 4 7
7 5 7
7 6 7
7 7 7
7 8 7
7 9 7
7 10 7
7 11 7
7 12 7
7 13 7
7 14 7
7 15 7
7 16 7
7 17 7
7 18 7
7 19 7
8 0 8
8 1 8
8 2 8
8 3 8
8 4 8
8 5 8
8 6 8
8 7 8
8 8 8
8 9 8
8 10 8
8 11 8
8 12 8
8 13 8
8 14 8
8 15 8
8 16 8
8 17 8
8 18 8
8 19 8
9 0 0
9 1 0
9 2 0
9 3 0
9 4 0
9 5 0
9 6 0
9 7 0
9 8 0
9 9 0
9 10 0
9 11 0
9 12 0
9 13 0
9 14 0
9 15 0
9 16 0
9 17 0
9 18 0
9 19 0
10 0 1
10 1 1
10 2 1
10 3 1
10 4 1
10 5 1
10 6 1
10 7 1
10 8 1
10 9 1
10 10 1
10 11 1
10 12 1
10 13 1
10 14 1
10 15 1
10 16 1
10 17 1
10 18 1
10 19 1
11 0 2
11 1 2
11 2 2
11 3 2
11 4 2
11 5 2
11 6 2
11 7 2
11 8 2
11 9 2
11 10 2
11 11 2
11 12 2
11 13 2
11 14 2
11 15 2
11 16 2
11 17 2
11 18 2
11 19 2
12 0 3
12 1 3
12 2 3
12 3 3
12 4 3
12 5 3
12 6 3
12 7 3
12 8 3
12 9 3
12 10 3
12 11 3
12 12 3
12 13 3
12 14 3
12 15 3
12 16 3
12 17 3
12 18 3
12 19 3
13 0 4
13 1 4
13 2 4
13 3 4
13 4 4
13 5 4
13 6 4
13 7 4
13 8 4
13 9 4
13 10 4
13 11 4
13 12 4
13 13 4
13 14 4
13 15 4
13 16 4
13 17 4
13 18 4
13 19 4
14 0 5
14 1 5
14 2 5
14 3 5
14 4 5
14 5 5
14 6 5
14 7 5
14 8 5
14 9 5
14 10 5
14 11 5
14 12 5
14 13 5
14 14 5
14 15 5
14 16 5
14 17 5
14 18 5
14 19 5
15 0 6
15 1 6
15 2 6
15 3 6
15 4 6
15 5 6
15 6 6
15 7 6
15 8 6
15 9 6
15 10 6
15 11 6
15 12 6
15 13 6
15 14 6
15 15 6
15 16 6
15 17 6
15 18 6
15 19 6
16 0 7
16 1 7
16 2 7
16 3 7
16 4 7
16 5 7
16 6 7
16 7 7
16 8 7
16 9 7
16 10 7
16 11 7
16 12 7
16 13 7
16 14 7
16 15 7
16 16 7
16 17 7
16 18 7
16 19 7
17 0 8
17 1 8
17 2 8
17 3 8
17 4 8
17 5 8
17 6 8
17 7 8
17 8 8
17 9 8
17 10 8
17 11 8
17 12 8
17 13 8
17 14 8
17 15 8
17 16 8
17 17 8
17 18 8
17 19 8
18 0 0
18 1 0
18 2 0
18 3 0
18 4 0
18 5 0
18 6 0
18 7 0
18 8 0
18 9 0
18 10 0
18 11 0
18 12 0
18 13 0
18 14 0
18 15 0
18 16 0
18 17 0
18 18 0
18 19 0
19 0 1
19 1 1
19 2 1
19 3 1
19 4 1
19 5 1
19 6 1
19 7 1
19 8 1
19 9 1
19 10 1
19 11 1
19 12 1
19 13 1
19 14 1
19 15 1
19 16 1
19 17 1
19 18 1
19 19 1
20 0 2
20 1 2
20 2 2
20 3 2
20 4 2
20 5 2
20 6 2
20 7 2
20 8 2
20 9 2
20 10 2
20 11 2
20 12 2
20 13 2
20 14 2
20 15 2
20 16 2
20 17 2
20 18 2
20 19 2
21 0 3
21 1 3
21 2 3
21 3 3
21 4 3
21 5 3
21 6 3
21 7 3
21 8 3
21 9 3
21 10 3
21 11 3
21 12 3
21 13 3
21 14 3
21 15 3
21 16 3
21 17 3
21 18 3
21 19 3
22 0 4
22 1 4
22 2 4
22 3 4
22 4 4
22 5 4
22 6 4
22 7 4
22 8 4
22 9 4
22 10 4
22 11 4
22 12 4
22 13 4
22 14 4
22 15 4
22 16 4
22 17 4
22 18 4
22 19 4
23 0 5
23 1 5
23 2 5
23 3 5
23 4 5
23 5 5
23 6 5
23 7 5
23 8 5
23 9 5
23 10 5
23 11 5
23 12 5
23 13 5
23 14 5
23 15 5
23 16 5
23 17 5
23 18 5
23 19 5
24 0 6
24 1 6
24 2 6
24 3 6
24 4 6
24 5 6
24 6 6
24 7 6
24 8 6
24 9 6
24 10 6
24 11 6
24 12 6
24 13 6
24 14 6
24 15 6
24 16 6
24 17 6
24 18 6
24 19 6
25 0 7
25 1 7
25 2 7
25 3 7
25 4 7
25 5 7
25 6 7
25 7 7
25 8 7
25 9 7
25 10 7
25 11 7
25 12 7
25 13 7
25 14 7
25 15 7
25 16 7
25 17 7
25 18 7
25 19 7
26 0 8
26 1 8
26 2 8
26 3 8
26 4 8
26 5 8
26 6 8
26 7 8
26 8 8
26 9 8
26 10 8
26 11 8
26 12 8
26 13 8
26 14 8
26 15 8
26 16 8
26 17 8
26 18 8
26 19 8

In [44]:
# Make DataFrame from list data
zomato_df = pd.DataFrame({
    "Name": restr_names,
    "Aggregate Rating": rating,
    "Type": cuisine_type,
    "Price": price_range,
    "Latitude": restr_lat,
    "Longitude": restr_lon,
    "Sensor ID": sensor_id,
    "Sensor": sensor_loc
})

zomato_df.tail(10)

,Name,Aggregate Rating,Type,Price,Latitude,Longitude,Sensor ID,Sensor
530,Geloso Gelateria,3.9,"Ice Cream, Desserts, Coffee and Tea",1,-37.8073125344,144.9577355012,51,QVM-Franklin St (North)
531,Pinball Paradise,3.7,Bar Food,1,-37.8096448882,144.9578672648,51,QVM-Franklin St (North)
532,Koko Black,3.9,Desserts,1,-37.8068651273,144.9591815472,51,QVM-Franklin St (North)
533,M&G Caiafa,3.7,Bakery,1,-37.8068423463,144.9592247978,51,QVM-Franklin St (North)
534,Narocha Premium Tea Room,4.1,"Bubble Tea, Cafe Food, Coffee and Tea",1,-37.8071022084,144.9601763114,51,QVM-Franklin St (North)
535,Simply Spanish,3.9,"Spanish, Tapas",3,-37.8068953254,144.9596127123,51,QVM-Franklin St (North)
536,Market Lane Coffee,4.0,Coffee and Tea,2,-37.8068296313,144.9591165036,51,QVM-Franklin St (North)
537,NeNe Chicken,3.2,"Korean, Fried Chicken",2,-37.8090133985,144.9609286711,51,QVM-Franklin St (North)
538,Andrew's Bread Shop,3.7,Bakery,1,-37.8068166514,144.9591285735,51,QVM-Franklin St (North)
539,Ferguson Plarre Bakehouse,3.6,"Bakery, Fast Food",1,-37.8067893672,144.9591644481,51,QVM-Franklin St (North)

In [45]:
# Drop duplicates from DataFrame
z_clean = zomato_df.drop_duplicates(subset="Name", keep=False).copy()
z_clean.count()

Name                399
Aggregate Rating    399
Type                399
Price               399
Latitude            399
Longitude           399
Sensor ID           399
Sensor              399
dtype: int64

In [46]:
# Change column types of Rating, Latitude and Longitude from strings to numbers (float)
z_clean["Aggregate Rating"] = z_clean["Aggregate Rating"].astype(float)
z_clean["Latitude"] = z_clean["Latitude"].astype(float)
z_clean["Longitude"] = z_clean["Longitude"].astype(float)
z_clean

,Name,Aggregate Rating,Type,Price,Latitude,Longitude,Sensor ID,Sensor
10,Hungry Jack's,3.2,"Fast Food, Burger",2,-37.812758,144.967896,21,Bourke St-Russell St (West)
11,Udon Yasan,4.0,Japanese,2,-37.812772,144.967762,21,Bourke St-Russell St (West)
12,Heroes,3.0,"Asian, Malaysian, Singaporean",3,-37.812770,144.967708,21,Bourke St-Russell St (West)
13,Tiger Tea è™Žå°‡,3.4,"Bubble Tea, Beverages",1,-37.812596,144.967410,21,Bourke St-Russell St (West)
14,Two Peck Crispy Chicken,3.4,Taiwanese,1,-37.812487,144.967358,21,Bourke St-Russell St (West)
...,...,...,...,...,...,...,...,...
534,Narocha Premium Tea Room,4.1,"Bubble Tea, Cafe Food, Coffee and Tea",1,-37.807102,144.960176,51,QVM-Franklin St (North)
535,Simply Spanish,3.9,"Spanish, Tapas",3,-37.806895,144.959613,51,QVM-Franklin St (North)
537,NeNe Chicken,3.2,"Korean, Fried Chicken",2,-37.809013,144.960929,51,QVM-Franklin St (North)
538,Andrew's Bread Shop,3.7,Bakery,1,-37.806817,144.959129,51,QVM-Franklin St (North)
539,Ferguson Plarre Bakehouse,3.6,"Bakery, Fast Food",1,-37.806789,144.959164,51,QVM-Franklin St (North)

In [34]:
### exporting this to a csv file
z_clean.to_csv("Testing_censorcsv/zomatowithsensor_csv", encoding="utf-8", index=False, header=True)

In [54]:
# List all unique eatery types for further reduction into broader categories
pd.set_option('display.max_rows', None)
list(z_clean["Type"].sort_values().unique())

['American, Italian',
 'Argentine, BBQ, Spanish',
 'Asian',
 'Asian Fusion, Modern Australian',
 'Asian, Chinese',
 'Asian, Chinese, Sichuan',
 'Asian, Chinese, Yum Cha',
 'Asian, Coffee and Tea, Cafe Food',
 'Asian, Desserts',
 'Asian, Desserts, Ice Cream',
 'Asian, Indonesian',
 'Asian, Malaysian, Singaporean',
 'Asian, Pan Asian, Vietnamese',
 'Asian, Singaporean, Malaysian',
 'Asian, Sushi',
 'Asian, Thai',
 'Asian, Vietnamese',
 'BBQ, American',
 'BBQ, European',
 'Bakery',
 'Bakery, Coffee and Tea',
 'Bakery, Desserts',
 'Bakery, Desserts, Coffee and Tea',
 'Bakery, Desserts, Japanese',
 'Bakery, Fast Food',
 'Bakery, Middle Eastern',
 'Bakery, Sandwich',
 'Bakery, Turkish',
 'Bar Food',
 'Bar Food, Burger',
 'Bar Food, German',
 'Bar Food, Latin American',
 'Bar Food, Modern Australian',
 'Beverages',
 'Beverages, Bubble Tea',
 'Beverages, Coffee and Tea, Desserts, Spanish',
 'Beverages, Healthy Food, Salad',
 'Bubble Tea',
 'Bubble Tea, Asian',
 'Bubble Tea, Beverages',
 'Bubble Tea, Cafe Food, Coffee and Tea',
 'Bubble Tea, Taiwanese',
 'Bubble Tea, Tea, Beverages',
 'Burger',
 'Burger, Bar Food',
 'Burger, Coffee and Tea',
 'Burger, Fast Food',
 'Cafe Food',
 'Cafe Food, Coffee and Tea',
 'Cafe Food, Coffee and Tea, Sandwich',
 'Cafe Food, Desserts, Coffee and Tea',
 'Cafe Food, Italian',
 'Cafe Food, Japanese, Tea',
 'Cafe Food, Salad, Coffee and Tea',
 'Chinese',
 'Chinese, Asian',
 'Chinese, Asian, Hot Pot, Dumplings, Sichuan',
 'Chinese, BBQ',
 'Chinese, BBQ, Cantonese',
 'Chinese, BBQ, Sichuan, Asian',
 'Chinese, Cantonese, Coffee and Tea',
 'Chinese, Coffee and Tea',
 'Chinese, Dumplings',
 'Chinese, Dumplings, Hot Pot',
 'Chinese, Hot Pot',
 'Chinese, Hot Pot, Asian, BBQ, Cabinet Food',
 'Chinese, Malatang',
 'Chinese, Malaysian',
 'Chinese, Shanghai, Dumplings',
 'Chinese, Street Food',
 'Chinese, Yum Cha',
 'Chinese, Yum Cha, Asian',
 'Chinese, Yum Cha, Hot Pot',
 'Coffee and Tea',
 'Coffee and Tea, Bakery, Sandwich',
 'Coffee and Tea, Beverages',
 'Coffee and Tea, Cafe Food',
 'Coffee and Tea, Cafe Food, Sandwich',
 'Coffee and Tea, Healthy Food, Salad, Sandwich',
 'Coffee and Tea, Italian, Cafe Food',
 'Coffee and Tea, Sandwich',
 'Coffee and Tea, Sandwich, Cafe Food',
 'Contemporary',
 'Contemporary, European, French',
 'Contemporary, Italian, Australian',
 'Continental',
 'Continental, Coffee and Tea, Cafe Food',
 'Desserts',
 'Desserts, Bakery',
 'Desserts, Beverages, Taiwanese',
 'Desserts, Coffee and Tea',
 'Desserts, Coffee and Tea, Cafe Food',
 'Desserts, Fast Food',
 'Desserts, French, Coffee and Tea',
 'Desserts, Ice Cream',
 'Desserts, Patisserie',
 'Desserts, Taiwanese',
 'Drinks Only',
 'Dumplings, Chinese',
 'Dumplings, Chinese, Asian',
 'European',
 'European, Cafe Food, Coffee and Tea',
 'European, Coffee and Tea',
 'European, Contemporary',
 'European, French, Italian',
 'European, German',
 'European, Italian',
 'European, Swiss',
 'Falafel, Kebab',
 'Fast Food',
 'Fast Food, Burger',
 'Fast Food, Fried Chicken',
 'Fast Food, German, Eastern European',
 'Fast Food, Italian, Pizza',
 'Fast Food, Japanese, Sushi',
 'Fast Food, Mexican',
 'Fast Food, Taiwanese, Fried Chicken',
 'Fish and Chips',
 'French, Cafe Food, Crepes, Desserts, Coffee and Tea',
 'French, Crepes',
 'French, Crepes, Coffee and Tea, Cafe Food',
 'French, European',
 'Fried Chicken, Korean, Asian',
 'German',
 'Greek',
 'Greek, Street Food',
 'Healthy Food',
 'Healthy Food, Fast Food, Salad',
 'Healthy Food, Juices',
 'Healthy Food, Salad',
 'Hot Pot',
 'Hot Pot, Japanese, Asian',
 'Hot Pot, Sichuan',
 'Ice Cream, Desserts',
 'Ice Cream, Desserts, Coffee and Tea',
 'Indian',
 'Indian, Burmese',
 'Indian, Coffee and Tea',
 'Indian, Contemporary',
 'Indian, Fast Food',
 'Indian, Healthy Food, Vegetarian',
 'Indonesian',
 'Indonesian, Malaysian',
 'Iranian',
 'Irish',
 'Italian',
 'Italian, Bar Food',
 'Italian, Cafe Food',
 'Italian, Coffee and Tea, Cafe Food',
 'Italian, Mediterranean, Pizza',
 'Italian, Modern Australian',
 'Italian, Pizza',
 'Italian, Pizza, Bar Food',
 'Italian, Pizza, Cafe Food',
 'Italian, Pizza, Seafood',
 'Italian, Seafood, Crepes, Parma',
 'Italian, Steak',
 'Japanese',
 'Japanese, Asian',
 'Japanese, Cafe Food, Coffee and Tea',
 'Japanese, Contemporary',
 'Japanese, Desserts, Coffee and Tea',
 'Japanese, Dumplings',
 'Japanese, Italian',
 'Japanese, Ramen',
 'Japanese, Sushi',
 'Japanese, Sushi, Japanese BBQ',
 'Japanese, Sushi, Teppanyaki',
 'Japanese, Teppanyaki',
 'Japanese, Teppanyaki, Sushi',
 'Juices',
 'Juices, Beverages, Desserts, Frozen Yogurt',
 'Juices, Coffee and Tea, Cafe Food',
 'Juices, Healthy Food',
 'Kebab',
 'Kebab, Coffee and Tea',
 'Korean',
 'Korean BBQ, Korean',
 'Korean, Asian',
 'Korean, Fried Chicken',
 'Korean, Korean BBQ',
 'Latin American',
 'Latin American, Mexican',
 'Latin American, Peruvian',
 'Lebanese, Egyptian, Mediterranean',
 'Malaysian',
 'Mediterranean, Cafe Food, Coffee and Tea',
 'Mediterranean, Coffee and Tea, Cafe Food',
 'Mexican',
 'Middle Eastern',
 'Modern Australian',
 'Modern Australian, Bar Food',
 'Modern Australian, Cafe Food, Coffee and Tea',
 'Modern Australian, European, Pizza',
 'Modern Australian, Italian',
 'Modern Australian, Tea',
 'Modern European, Bar Food',
 'Modern European, Contemporary',
 'Nepalese',
 'Pizza',
 'Pizza, Grill',
 'Pizza, Modern Australian',
 'Pub Food',
 'Pub Food, Belgian, Australian',
 'Pub Food, Modern Australian',
 'Ramen, Japanese',
 'Sandwich',
 'Sandwich, Burger',
 'Sandwich, Burger, American',
 'Sandwich, Coffee and Tea, Cafe Food',
 'Sandwich, Fast Food',
 'Seafood',
 'Seafood, Modern Australian',
 'Seafood, Steak, Modern Australian',
 'Spanish, Tapas',
 'Steak',
 'Steak, Bar Food, Grill',
 'Steak, Eastern European',
 'Sushi',
 'Sushi, Japanese',
 'Taiwanese',
 'Taiwanese, Chinese, Asian, Street Food',
 'Tea',
 'Tea, Bubble Tea, Beverages',
 'Thai',
 'Thai, Asian',
 'Thai, BBQ, Hot Pot',
 'Turkish, Middle Eastern',
 'Vegetarian, Coffee and Tea, Cafe Food',
 'Vietnamese',
 'Vietnamese, Healthy Food',
 'Vietnamese, Pho',
 'Vietnamese, Sandwich']

In [58]:
# Reduce eateries to the following types: 
# restaurant (regardless of ethnicity), cafe, beverages (including bubble tea, juices, etc.), 
# bar, bakery, desserts, pub, fast food (takeaway),

z_clean_reduced = z_clean.replace({'American, Italian':'Restaurant',
    'Argentine, BBQ, Spanish':'Restaurant',
    'Asian':'Restaurant',
    'Asian Fusion, Modern Australian':'Restaurant',
    'Asian, Chinese':'Restaurant',
    'Asian, Chinese, Sichuan':'Restaurant',
    'Asian, Chinese, Yum Cha':'Restaurant',
    'Asian, Coffee and Tea, Cafe Food':'Cafe',
    'Asian, Desserts':'Desserts',
    'Asian, Desserts, Ice Cream':'Desserts',
    'Asian, Indonesian':'Restaurant',
    'Asian, Malaysian, Singaporean':'Restaurant',
    'Asian, Pan Asian, Vietnamese':'Restaurant',
    'Asian, Singaporean, Malaysian':'Restaurant',
    'Asian, Sushi':'Restaurant',
    'Asian, Thai':'Restaurant',
    'Asian, Vietnamese':'Restaurant',
    'BBQ, American':'Restaurant',
    'BBQ, European':'Restaurant',
    'Bakery, Coffee and Tea':'Bakery',
    'Bakery, Desserts':'Bakery',
    'Bakery, Desserts, Coffee and Tea':'Bakery',
    'Bakery, Desserts, Japanese':'Bakery',
    'Bakery, Fast Food':'Fast Food',
    'Bakery, Middle Eastern':'Bakery',
    'Bakery, Sandwich':'Bakery',
    'Bakery, Turkish':'Bakery',
    'Bar Food':'Bar',
    'Bar Food, Burger':'Bar',
    'Bar Food, German':'Bar',
    'Bar Food, Latin American':'Bar',
    'Bar Food, Modern Australian':'Bar',
    'Beverages, Bubble Tea':'Beverages',
    'Beverages, Coffee and Tea, Desserts, Spanish':'Beverages',
    'Beverages, Healthy Food, Salad':'Beverages',
    'Bubble Tea':'Beverages',
    'Bubble Tea, Asian':'Beverages',
    'Bubble Tea, Beverages':'Beverages',
    'Bubble Tea, Cafe Food, Coffee and Tea':'Beverages',
    'Bubble Tea, Taiwanese':'Beverages',
    'Bubble Tea, Tea, Beverages':'Beverages',
    'Burger':'Fast Food',
    'Burger, Bar Food':'Fast Food',
    'Burger, Coffee and Tea':'Fast Food',
    'Burger, Fast Food':'Fast Food',
    'Cafe Food':'Cafe',
    'Cafe Food, Coffee and Tea':'Cafe',
    'Cafe Food, Coffee and Tea, Sandwich':'Cafe',
    'Cafe Food, Desserts, Coffee and Tea':'Cafe',
    'Cafe Food, Italian':'Cafe',
    'Cafe Food, Japanese, Tea':'Cafe',
    'Cafe Food, Salad, Coffee and Tea':'Cafe',
    'Chinese':'Restaurant',
    'Chinese, Asian':'Restaurant',
    'Chinese, Asian, Hot Pot, Dumplings, Sichuan':'Restaurant',
    'Chinese, BBQ':'Restaurant',
    'Chinese, BBQ, Cantonese':'Restaurant',
    'Chinese, BBQ, Sichuan, Asian':'Restaurant',
    'Chinese, Cantonese, Coffee and Tea':'Restaurant',
    'Chinese, Coffee and Tea':'Restaurant',
    'Chinese, Dumplings':'Restaurant',
    'Chinese, Dumplings, Hot Pot':'Restaurant',
    'Chinese, Hot Pot':'Restaurant',
    'Chinese, Hot Pot, Asian, BBQ, Cabinet Food':'Restaurant',
    'Chinese, Malatang':'Restaurant',
    'Chinese, Malaysian':'Restaurant',
    'Chinese, Shanghai, Dumplings':'Restaurant',
    'Chinese, Street Food':'Restaurant',
    'Chinese, Yum Cha':'Restaurant',
    'Chinese, Yum Cha, Asian':'Restaurant',
    'Chinese, Yum Cha, Hot Pot':'Restaurant',
    'Coffee and Tea':'Cafe',
    'Coffee and Tea, Bakery, Sandwich':'Cafe',
    'Coffee and Tea, Beverages':'Cafe',
    'Coffee and Tea, Cafe Food':'Cafe',
    'Coffee and Tea, Cafe Food, Sandwich':'Cafe',
    'Coffee and Tea, Healthy Food, Salad, Sandwich':'Cafe',
    'Coffee and Tea, Italian, Cafe Food':'Cafe',
    'Coffee and Tea, Sandwich':'Cafe',
    'Coffee and Tea, Sandwich, Cafe Food':'Cafe',
    'Contemporary':'Restaurant',
    'Contemporary, European, French':'Restaurant',
    'Contemporary, Italian, Australian':'Restaurant',
    'Continental':'Restaurant',
    'Continental, Coffee and Tea, Cafe Food':'Cafe',
    'Desserts, Bakery':'Desserts',
    'Desserts, Beverages, Taiwanese':'Desserts',
    'Desserts, Coffee and Tea':'Desserts',
    'Desserts, Coffee and Tea, Cafe Food':'Desserts',
    'Desserts, Fast Food':'Desserts',
    'Desserts, French, Coffee and Tea':'Desserts',
    'Desserts, Ice Cream':'Desserts',
    'Desserts, Patisserie':'Desserts',
    'Desserts, Taiwanese':'Desserts',
    'Drinks Only':'Beverages',
    'Dumplings, Chinese':'Restaurant',
    'Dumplings, Chinese, Asian':'Restaurant',
    'European':'Restaurant',
    'European, Cafe Food, Coffee and Tea':'Cafe',
    'European, Coffee and Tea':'Cafe',
    'European, Contemporary':'Cafe',
    'European, French, Italian':'Cafe',
    'European, German':'Cafe',
    'European, Italian':'Cafe',
    'European, Swiss':'Cafe',
    'Falafel, Kebab':'Cafe',
    'Fast Food, Burger':'Fast Food',
    'Fast Food, Fried Chicken':'Fast Food',
    'Fast Food, German, Eastern European':'Fast Food',
    'Fast Food, Italian, Pizza':'Fast Food',
    'Fast Food, Japanese, Sushi':'Fast Food',
    'Fast Food, Mexican':'Fast Food',
    'Fast Food, Taiwanese, Fried Chicken':'Fast Food',
    'Fish and Chips':'Fast Food',
    'French, Cafe Food, Crepes, Desserts, Coffee and Tea':'Cafe',
    'French, Crepes':'Restaurant',
    'French, Crepes, Coffee and Tea, Cafe Food':'Cafe',
    'French, European':'Cafe',
    'Fried Chicken, Korean, Asian':'Restaurant',
    'German':'Restaurant',
    'Greek':'Restaurant',
    'Greek, Street Food':'Restaurant',
    'Healthy Food':'Restaurant',
    'Healthy Food, Fast Food, Salad':'Fast Food',
    'Healthy Food, Juices':'Beverages',
    'Healthy Food, Salad':'Fast Food',
    'Hot Pot':'Restaurant',
    'Hot Pot, Japanese, Asian':'Restaurant',
    'Hot Pot, Sichuan':'Restaurant',
    'Ice Cream, Desserts':'Desserts',
    'Ice Cream, Desserts, Coffee and Tea':'Desserts',
    'Indian':'Restaurant',
    'Indian, Burmese':'Restaurant',
    'Indian, Coffee and Tea':'Cafe',
    'Indian, Contemporary':'Restaurant',
    'Indian, Fast Food':'Fast Food',
    'Indian, Healthy Food, Vegetarian':'Restaurant',
    'Indonesian':'Restaurant',
    'Indonesian, Malaysian':'Restaurant',
    'Iranian':'Restaurant',
    'Irish':'Restaurant',
    'Italian':'Restaurant',
    'Italian, Bar Food':'Bar',
    'Italian, Cafe Food':'Cafe',
    'Italian, Coffee and Tea, Cafe Food':'Cafe',
    'Italian, Mediterranean, Pizza':'Restaurant',
    'Italian, Modern Australian':'Restaurant',
    'Italian, Pizza':'Restaurant',
    'Italian, Pizza, Bar Food':'Bar',
    'Italian, Pizza, Cafe Food':'Cafe',
    'Italian, Pizza, Seafood':'Restaurant',
    'Italian, Seafood, Crepes, Parma':'Restaurant',
    'Italian, Steak':'Restaurant',
    'Japanese':'Restaurant',
    'Japanese, Asian':'Restaurant',
    'Japanese, Cafe Food, Coffee and Tea':'Cafe',
    'Japanese, Contemporary':'Restaurant',
    'Japanese, Desserts, Coffee and Tea':'Cafe',
    'Japanese, Dumplings':'Restaurant',
    'Japanese, Italian':'Restaurant',
    'Japanese, Ramen':'Restaurant',
    'Japanese, Sushi':'Restaurant',
    'Japanese, Sushi, Japanese BBQ':'Restaurant',
    'Japanese, Sushi, Teppanyaki':'Restaurant',
    'Japanese, Teppanyaki':'Restaurant',
    'Japanese, Teppanyaki, Sushi':'Restaurant',
    'Juices':'Beverages',
    'Juices, Beverages, Desserts, Frozen Yogurt':'Beverages',
    'Juices, Coffee and Tea, Cafe Food':'Beverages',
    'Juices, Healthy Food':'Beverages',
    'Kebab':'Fast Food',
    'Kebab, Coffee and Tea':'Cafe',
    'Korean':'Restaurant',
    'Korean BBQ, Korean':'Restaurant',
    'Korean, Asian':'Restaurant',
    'Korean, Fried Chicken':'Restaurant',
    'Korean, Korean BBQ':'Restaurant',
    'Latin American':'Restaurant',
    'Latin American, Mexican':'Restaurant',
    'Latin American, Peruvian':'Restaurant',
    'Lebanese, Egyptian, Mediterranean':'Restaurant',
    'Malaysian':'Restaurant',
    'Mediterranean, Cafe Food, Coffee and Tea':'Cafe',
    'Mediterranean, Coffee and Tea, Cafe Food':'Cafe',
    'Mexican':'Restaurant',
    'Middle Eastern':'Restaurant',
    'Modern Australian':'Restaurant',
    'Modern Australian, Bar Food':'Bar',
    'Modern Australian, Cafe Food, Coffee and Tea':'Cafe',
    'Modern Australian, European, Pizza':'Restaurant',
    'Modern Australian, Italian':'Restaurant',
    'Modern Australian, Tea':'Restaurant',
    'Modern European, Bar Food':'Bar',
    'Modern European, Contemporary':'Restaurant',
    'Nepalese':'Restaurant',
    'Pizza':'Restaurant',
    'Pizza, Grill':'Restaurant',
    'Pizza, Modern Australian':'Restaurant',
    'Pub Food':'Pub',
    'Pub Food, Belgian, Australian':'Pub',
    'Pub Food, Modern Australian':'Pub',
    'Ramen, Japanese':'Restaurant',
    'Sandwich':'Fast Food',
    'Sandwich, Burger':'Fast Food',
    'Sandwich, Burger, American':'Fast Food',
    'Sandwich, Coffee and Tea, Cafe Food':'Fast Food',
    'Sandwich, Fast Food':'Fast Food',
    'Seafood':'Restaurant',
    'Seafood, Modern Australian':'Restaurant',
    'Seafood, Steak, Modern Australian':'Restaurant',
    'Spanish, Tapas':'Restaurant',
    'Steak':'Restaurant',
    'Steak, Bar Food, Grill':'Restaurant',
    'Steak, Eastern European':'Restaurant',
    'Sushi':'Restaurant',
    'Sushi, Japanese':'Restaurant',
    'Taiwanese':'Restaurant',
    'Taiwanese, Chinese, Asian, Street Food':'Restaurant',
    'Tea':'Beverages',
    'Tea, Bubble Tea, Beverages':'Beverages',
    'Thai':'Restaurant',
    'Thai, Asian':'Restaurant',
    'Thai, BBQ, Hot Pot':'Restaurant',
    'Turkish, Middle Eastern':'Restaurant',
    'Vegetarian, Coffee and Tea, Cafe Food':'Cafe',
    'Vietnamese':'Restaurant',
    'Vietnamese, Healthy Food':'Restaurant',
    'Vietnamese, Pho':'Restaurant',
    'Vietnamese, Sandwich':'Cafe'})

z_clean_reduced.Type.value_counts()

Restaurant    209
Cafe           73
Fast Food      31
Beverages      26
Bar            25
Desserts       21
Bakery         10
Pub             4
Name: Type, dtype: int64

In [60]:
z_clean_reduced.head()

,Name,Aggregate Rating,Type,Price,Latitude,Longitude,Sensor ID,Sensor
10,Hungry Jack's,3.2,Fast Food,2,-37.812758,144.967896,21,Bourke St-Russell St (West)
11,Udon Yasan,4.0,Restaurant,2,-37.812772,144.967762,21,Bourke St-Russell St (West)
12,Heroes,3.0,Restaurant,3,-37.812770,144.967708,21,Bourke St-Russell St (West)
13,Tiger Tea è™Žå°‡,3.4,Beverages,1,-37.812596,144.967410,21,Bourke St-Russell St (West)
14,Two Peck Crispy Chicken,3.4,Restaurant,1,-37.812487,144.967358,21,Bourke St-Russell St (West)

In [61]:
# Save Zomato DataFrame (Unconsolidated Types) to CSV
z_clean_csv = z_clean.to_csv("Output/csv/Zomato_Restaurants_All.csv")
# Save Zomato DataFrame (Consolidated Types)
z_clean_types_csv = z_clean_reduced.to_csv("Output/csv/Zomato_Restaurants_All_Consolidated-Types.csv")