In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
from scipy import stats
import numpy as np
import requests
import pandas as pd
import json
from citipy import citipy
import random

# Import API key
from config import api_key

In [2]:
# Base URL required for API call
url = "https://developers.zomato.com/api/v2.1/search?"

# Parameters to run through Query URL
start = np.arange(0,20,20)
count = 20
city = 259
lat = -37.8136
lon = 144.9631
radius = 2500

# Empty list to hold all API calls
response_data = []

# Loop through Zomato API
for a in range(len(start)):
    query_url = f"{url}entity_id={city}&entity_type=metro&lat={lat}&lon={lon}&radius={radius}&sort=real_distance&apikey={api_key}&start={start[a]}&count={count}"
    response_data.append(requests.get(query_url).json())

In [3]:
type(count)

int

In [4]:
# Empty list to hold all restaurant names, aggregate rating, hours of operation, type of eatery, price 
restr_names = []
rating = []
cuisine_type = []
price_range = []
restr_lat = []
restr_lon = []
b = 0

for a in range(len(start)):
    for x in range(count):
        restr_names.append(response_data[b]["restaurants"][x]["restaurant"]["name"])
        rating.append(response_data[b]["restaurants"][x]["restaurant"]["user_rating"]["aggregate_rating"])
        cuisine_type.append(response_data[b]["restaurants"][x]["restaurant"]["cuisines"])
        price_range.append(response_data[b]["restaurants"][x]["restaurant"]["price_range"])
        restr_lat.append(response_data[b]["restaurants"][x]["restaurant"]["location"]["latitude"])
        restr_lon.append(response_data[b]["restaurants"][x]["restaurant"]["location"]["longitude"])        
    b += 1

In [5]:
zomato_df = pd.DataFrame({
    "Name": restr_names,
    "Aggregate Rating": rating,
    "Type": cuisine_type,
    "Price": price_range,
    "Latitude": restr_lat,
    "Longitude": restr_lon,
})

zomato_df

,Name,Aggregate Rating,Type,Price,Latitude,Longitude
0,Sparrows Philly Cheese Steaks Food Truck,3.1,"American, Steak",3,-37.8136223020,144.9630647153
1,Moo Mii Sushi,0,"Japanese, Sushi",1,-37.8136093233,144.9632383883
2,Schnitz,4.0,"Sandwich, Fast Food",2,-37.8137094446,144.9627552554
3,Yifang Taiwan Fruit Tea - Elizabth 一芳臺灣水果茶,3.3,"Bubble Tea, Asian",1,-37.8136887847,144.9627391622
4,Tropicana Juice Food Bar,4.4,"Juices, Cafe Food",2,-37.8135600573,144.9626938999
5,Subway,2.9,Sandwich,2,-37.8139902073,144.9628943950
6,Captains of Industry,4.4,"Sandwich, Coffee and Tea, Cafe Food",2,-37.8136310428,144.9625473842
7,Federal Coffee,4.0,"Coffee and Tea, Cafe Food",2,-37.8140357649,144.9633436650
8,Udon Yasan,3.9,"Asian, Japanese",2,-37.8140484786,144.9628819898
9,Ca de Vin,4.2,Mediterranean,4,-37.8138185714,144.9636578187
10,Sweet Canteen,4.0,Patisserie,1,-37.8130909684,144.9631465226
11,Cartel Coffee Roasters,4.2,"Sandwich, Coffee and Tea, Cafe Food",2,-37.8138556532,144.9625306204
12,Brunetti,4.0,"Desserts, Coffee and Tea, Cafe Food",2,-37.8135505219,144.9638036639
13,Shanghai Street Dumpling & Mini Juicy Bun,4.5,"Chinese, Dumplings",3,-37.8133039261,144.9624219909
14,Hana's Kitchen,3.8,Asian,3,-37.8133407434,144.9623750523
15,Beneath Driver Lane,4.0,"Bar Food, French",3,-37.8129352228,144.9630489573
16,The Salon Bar & Cafe,3.9,"Sandwich, Coffee and Tea",3,-37.8134959583,144.9639575556
17,Little Ramen Bar,4.3,"Japanese, Ramen",3,-37.8133545167,144.9622895569
18,Luis BBQ & Pizza,3.2,"BBQ, Pizza, Fast Food",2,-37.8130771950,144.9624618888
19,Shanghai Street on Bourke,4.1,"Chinese, Dumplings",3,-37.8142908340,144.9627706781

In [7]:
restr_names

['Sparrows Philly Cheese Steaks Food Truck',
 'Moo Mii Sushi',
 'Schnitz',
 'Yifang Taiwan Fruit Tea - Elizabth 一芳臺灣水果茶',
 'Tropicana Juice Food Bar',
 'Subway',
 'Captains of Industry',
 'Federal Coffee',
 'Udon Yasan',
 'Ca de Vin',
 'Sweet Canteen',
 'Cartel Coffee Roasters',
 'Brunetti',
 'Shanghai Street Dumpling & Mini Juicy Bun',
 "Hana's Kitchen",
 'Beneath Driver Lane',
 'The Salon Bar & Cafe',
 'Little Ramen Bar',
 'Luis BBQ & Pizza',
 'Shanghai Street on Bourke']