In [21]:
import pandas as pd
from sodapy import Socrata

In [19]:
# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("data.melbourne.vic.gov.au", None)

MyAppToken = "95TJNF2CEl6aUWA4cHIZFJzsw"

# Example authenticated client (needed for non-public datasets):
client = Socrata("data.melbourne.vic.gov.au",
               MyAppToken,
               username="nkoleits@gmail.com",
               password="")

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("xt2y-tnn9", limit=80000)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [28]:
results_df.head()

,census_year,block_id,property_id,base_property_id,street_address,clue_small_area,trading_name,industry_anzsic4_code,industry_anzsic4_description,seating_type,number_of_seats,x_coordinate,y_coordinate,geocoded_column
0,2002,203,109358,109358,832-834 Swanston Street CARLTON 3053,Carlton,Unibite,4512,Takeaway Food Services,Seats - Indoor,30,144.9649,-37.7967,"{'type': 'Point', 'coordinates': [144.9649, -3..."
1,2002,204,101613,101613,377-391 Cardigan Street CARLTON 3053,Carlton,Clyde Hotel,4520,"Pubs, Taverns and Bars",Seats - Indoor,50,144.9658,-37.7973,"{'type': 'Point', 'coordinates': [144.9658, -3..."
2,2002,205,104469,104469,114-152 Grattan Street CARLTON 3053,Carlton,Royal Women's Hospital Coffee Shop,4512,Takeaway Food Services,Seats - Indoor,25,144.9648,-37.8,"{'type': 'Point', 'coordinates': [144.9648, -3..."
3,2002,206,103691,103691,221-229 Faraday Street CARLTON 3053,Carlton,Thresherman's Bakehouse,4511,Cafes and Restaurants,Seats - Indoor,70,144.9667,-37.7989,"{'type': 'Point', 'coordinates': [144.9667, -3..."
4,2002,206,103691,103691,221-229 Faraday Street CARLTON 3053,Carlton,Thresherman's Bakehouse,4511,Cafes and Restaurants,Seats - Outdoor,42,144.9667,-37.7989,"{'type': 'Point', 'coordinates': [144.9667, -3..."

In [27]:
results_df.dtypes

census_year                     object
block_id                        object
property_id                     object
base_property_id                object
street_address                  object
clue_small_area                 object
trading_name                    object
industry_anzsic4_code           object
industry_anzsic4_description    object
seating_type                    object
number_of_seats                 object
x_coordinate                    object
y_coordinate                    object
geocoded_column                 object
dtype: object

In [32]:
results_df['census_year'] = pd.to_numeric(results_df['census_year'])

In [33]:
results_df[results_df['census_year'] > 2018]

,census_year,block_id,property_id,base_property_id,street_address,clue_small_area,trading_name,industry_anzsic4_code,industry_anzsic4_description,seating_type,number_of_seats,x_coordinate,y_coordinate,geocoded_column
47120,2019,203,103123,103123,258 Elgin Street CARLTON 3053,Carlton,Cafe Sua Da,4511,Cafes and Restaurants,Seats - Indoor,45,144.9655339,-37.79670704,"{'type': 'Point', 'coordinates': [144.9655339,..."
47121,2019,203,103123,103123,258 Elgin Street CARLTON 3053,Carlton,Cafe Sua Da,4511,Cafes and Restaurants,Seats - Outdoor,6,144.9655339,-37.79670704,"{'type': 'Point', 'coordinates': [144.9655339,..."
47122,2019,203,109358,109358,832-834 Swanston Street CARLTON 3053,Carlton,Brother Bull,4511,Cafes and Restaurants,Seats - Indoor,42,144.9649,-37.79668018,"{'type': 'Point', 'coordinates': [144.9649, -3..."
47123,2019,204,101613,101613,377-391 Cardigan Street CARLTON 3053,Carlton,Clyde Hotel,4520,"Pubs, Taverns and Bars",Seats - Indoor,70,144.9657543,-37.7972554,"{'type': 'Point', 'coordinates': [144.9657543,..."
47124,2019,204,101613,101613,377-391 Cardigan Street CARLTON 3053,Carlton,Clyde Hotel,4520,"Pubs, Taverns and Bars",Seats - Outdoor,50,144.9657543,-37.7972554,"{'type': 'Point', 'coordinates': [144.9657543,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50647,2019,861,102507,102507,185-189 Domain Road SOUTH YARRA VIC 3141,South Yarra,The Golden Triangle Restaurant,4511,Cafes and Restaurants,Seats - Indoor,60,144.9822639,-37.83434411,"{'type': 'Point', 'coordinates': [144.9822639,..."
50648,2019,862,102498,102498,131-133 Domain Road SOUTH YARRA VIC 3141,South Yarra,Entrecote - Paris Steakhouse & Winebar,4511,Cafes and Restaurants,Seats - Indoor,120,144.980491,-37.83412514,"{'type': 'Point', 'coordinates': [144.980491, ..."
50649,2019,862,102498,102498,131-133 Domain Road SOUTH YARRA VIC 3141,South Yarra,Entrecote - Paris Steakhouse & Winebar,4511,Cafes and Restaurants,Seats - Outdoor,30,144.980491,-37.83412514,"{'type': 'Point', 'coordinates': [144.980491, ..."
50650,2019,862,109532,109532,2-14 Hope Street SOUTH YARRA VIC 3141,South Yarra,Bistro Gitan,4511,Cafes and Restaurants,Seats - Outdoor,6,144.9793101,-37.83713828,"{'type': 'Point', 'coordinates': [144.9793101,..."
50651,2019,862,109532,109532,2-14 Hope Street SOUTH YARRA VIC 3141,South Yarra,Bistro Gitan,4511,Cafes and Restaurants,Seats - Indoor,74,144.9793101,-37.83713828,"{'type': 'Point', 'coordinates': [144.9793101,..."